# Generated by Django 3.1.3 on 2020-11-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='username',
        ),
    ]
