# Generated by Django 3.1.3 on 2020-11-03 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_telegramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
