# Generated by Django 3.1.3 on 2020-11-03 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramstate',
            name='telegram_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='django_messages_bot.telegramchat'),
        ),
        migrations.AlterField(
            model_name='telegramstate',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_states', to='django_messages_bot.telegramuser'),
        ),
    ]
